import * as api from './api.js';

const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const state = { source: 'file', result: null, historyRisk: '', blacklistKeyword: '', blacklistStatus: '', knowledgeCategory: '', knowledgeKeyword: '' };
const labels = { low: '低风险', medium: '中风险', high: '高风险', legitimate: '模型倾向正常', phishing: '模型倾向钓鱼', active: '启用', review: '待复核', false_positive: '误报' };

function text(value, fallback = '-') { return value === null || value === undefined || value === '' ? fallback : String(value); }
function el(tag, className, content) { const node = document.createElement(tag); if (className) node.className = className; if (content !== undefined) node.textContent = content; return node; }
function showToast(message, error = false) { const toast = $('#toast'); toast.textContent = message; toast.classList.toggle('error', error); toast.classList.add('show'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove('show'), 3000); }
function handleError(error) { showToast(`${error.message}${error.code ? ` · ${error.code}` : ''}`, true); }
function setLoading(isLoading) { $('#result-empty').classList.toggle('hidden', isLoading || Boolean(state.result)); $('#analysis-loading').classList.toggle('hidden', !isLoading); $('#result-content').classList.toggle('hidden', isLoading || !state.result); }

function switchView(name) {
  $$('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.view === name));
  $$('.view').forEach(view => view.classList.toggle('active', view.id === `view-${name}`));
  const copy = { analyze: ['静态邮件检测', '识别风险，从一封邮件开始。'], history: ['检测历史', '回看每一次风险判断。'], blacklist: ['离线黑名单', '管理用于静态匹配的指标。'], dashboard: ['统计看板', '把检测记录变成可读的趋势。'], knowledge: ['防范知识', '把一次检测变成长期判断力。'] }[name];
  $('#page-eyebrow').textContent = copy[0]; $('#page-title').textContent = copy[1];
  if (name === 'history') loadHistory(); if (name === 'blacklist') loadBlacklist(); if (name === 'dashboard') loadDashboard(); if (name === 'knowledge') loadKnowledge();
}

function setupInput() {
  $$('.source-option').forEach(button => button.addEventListener('click', () => { state.source = button.dataset.source; $$('.source-option').forEach(item => { item.classList.toggle('active', item === button); item.setAttribute('aria-selected', item === button ? 'true' : 'false'); }); $$('.source-pane').forEach(pane => pane.classList.toggle('active', pane.dataset.sourcePane === state.source)); }));
  const fileInput = $('#email-file'); const drop = $('#drop-zone');
  fileInput.addEventListener('change', () => { if (fileInput.files[0]) $('#file-label').textContent = fileInput.files[0].name; });
  ['dragenter', 'dragover'].forEach(type => drop.addEventListener(type, event => { event.preventDefault(); drop.classList.add('drag'); })); ['dragleave', 'drop'].forEach(type => drop.addEventListener(type, event => { event.preventDefault(); drop.classList.remove('drag'); }));
  drop.addEventListener('drop', event => { const file = event.dataTransfer.files[0]; if (file) { fileInput.files = event.dataTransfer.files; $('#file-label').textContent = file.name; } });
  $('#raw-email').addEventListener('input', event => { $('#text-count').textContent = event.target.value.length.toLocaleString('en-US'); });
  $('#analysis-form').addEventListener('submit', async event => { event.preventDefault(); const file = fileInput.files[0]; const raw = $('#raw-email').value; const sampleId = $('#sample-id').value.trim(); if (state.source === 'file' && !file) return showToast('请先选择一个 .eml 文件', true); if (state.source === 'text' && !raw.trim()) return showToast('请粘贴完整邮件原文', true); if (state.source === 'sample' && !sampleId) return showToast('请输入演示样本 ID', true); setLoading(true); try { state.result = state.source === 'file' ? await api.analyzeFile(file) : state.source === 'text' ? await api.analyzeText(raw) : await api.analyzeSample(sampleId); renderResult(state.result); showToast('静态分析完成'); } catch (error) { state.result = null; setLoading(false); handleError(error); } });
}

function renderResult(result) {
  setLoading(false); const root = $('#result-content'); root.replaceChildren();
  const summary = el('div', 'result-summary'); const risk = el('div', `risk-card ${result.risk_level}`); risk.append(el('div', 'risk-kicker', 'FUSED RISK SCORE')); const score = el('div', 'risk-score'); score.append(el('strong', '', Math.round(result.final_score)), el('span', '', '/ 100')); risk.append(score, el('p', 'risk-level', `${labels[result.risk_level] || result.risk_level} · ${labels[result.result_label] || result.result_label}`));
  const meta = el('div', 'panel result-meta'); [['模型概率', `${Math.round(result.model_probability * 100)}%`, 'phishing probability'], ['规则得分', `${Math.round(result.rule_score)} / 100`, 'deduplicated rule score'], ['模型版本', text(result.model_version), 'local pipeline']].forEach(([name, value, hint]) => { const block = el('div'); block.append(el('span', '', name), el('b', '', value), el('small', '', hint)); meta.append(block); }); summary.append(risk, meta); root.append(summary);
  const grid = el('div', 'detail-grid'); const evidence = el('section', 'panel detail-section'); evidence.append(el('h2', '', '风险证据')); const list = el('div', 'explanation-list'); (result.explanations || []).forEach(item => { const card = el('article', `explanation ${item.severity || 'warning'}`); card.append(el('b', '', `${item.code} · ${text(item.title)}`), el('p', '', text(item.detail))); if (item.evidence) card.append(el('span', 'evidence-text', item.evidence)); list.append(card); }); if (!list.children.length) list.append(el('p', 'muted-copy', '暂未发现规则命中，仍请结合模型概率和上下文判断。')); evidence.append(list);
  const advice = el('section', 'panel detail-section'); advice.append(el('h2', '', '处理建议')); const adviceList = el('ul', 'advice-list'); (result.advice || ['不要点击邮件中的链接或打开附件。']).forEach(item => adviceList.append(el('li', '', item))); advice.append(adviceList); if ((result.parse_warnings || []).length) { const warning = el('div', 'warning-box', `解析提醒：${result.parse_warnings.join('；')}`); advice.append(warning); } grid.append(evidence, advice); root.append(grid);
  const assets = el('div', 'detail-grid'); assets.append(renderUrls(result.urls || []), renderAttachments(result.attachments || [])); root.append(assets);
  const feedbackPanel = el('section', 'panel detail-section feedback-panel'); feedbackPanel.append(el('h2', '', '人工反馈')); const feedbackRow = el('div', 'feedback-row'); feedbackRow.append(el('span', '', '这个判断对你有帮助吗？')); ['confirmed_phishing', 'false_positive', 'unsure'].forEach(label => { const button = el('button', 'filter-button', { confirmed_phishing: '确认钓鱼', false_positive: '认为误报', unsure: '暂不确定' }[label]); button.addEventListener('click', async () => { try { await api.feedback({ detection_id: result.detection_id, label, note: '' }); feedbackRow.querySelectorAll('button').forEach(item => item.classList.remove('active')); button.classList.add('active'); showToast('反馈已记录'); } catch (error) { handleError(error); } }); feedbackRow.append(button); }); feedbackPanel.append(feedbackRow); root.append(feedbackPanel);
}

function renderUrls(urls) { const section = el('section', 'panel detail-section'); section.append(el('h2', '', `URL 静态信息 · ${urls.length}`)); const list = el('div', 'compact-list'); urls.forEach(url => { const row = el('div', 'data-row'); row.append(el('b', '', text(url.display_text || url.raw_url))); row.append(el('small', '', `${text(url.host)} · ${url.is_https ? 'HTTPS' : '非 HTTPS'}${url.blacklist_hit ? ' · 命中离线黑名单' : ''}`)); if (url.suspicious_tokens?.length) { const tags = el('div'); url.suspicious_tokens.forEach(token => tags.append(el('span', 'tag', token))); row.append(tags); } list.append(row); }); if (!urls.length) list.append(el('p', 'muted-copy', '未提取到 URL')); section.append(list); return section; }
function renderAttachments(items) { const section = el('section', 'panel detail-section'); section.append(el('h2', '', `附件元数据 · ${items.length}`)); const list = el('div', 'compact-list'); items.forEach(item => { const row = el('div', 'data-row'); row.append(el('b', '', text(item.filename))); row.append(el('small', '', `${text(item.mime_type)} · ${Number(item.size || 0).toLocaleString('en-US')} bytes`)); (item.risk_hints || []).forEach(hint => row.append(el('span', 'tag', hint))); list.append(row); }); if (!items.length) list.append(el('p', 'muted-copy', '未发现附件')); section.append(list); return section; }

async function loadHistory() { const host = $('#history-content'); host.replaceChildren(el('div', 'loading-state', '正在读取历史记录…')); try { const data = await api.listDetections(state.historyRisk); host.replaceChildren(); if (!data.items?.length) return host.append(el('div', 'empty-table', '还没有检测记录')); const table = el('table', 'data-table'); const head = el('thead'); const tr = el('tr'); ['主题', '风险', '分数', '资源', '时间', ''].forEach(name => tr.append(el('th', '', name))); head.append(tr); const body = el('tbody'); data.items.forEach(item => { const row = el('tr'); const subject = el('td', 'subject-cell', text(item.subject, '无主题')); const risk = el('td'); risk.append(el('span', `risk-pill ${item.risk_level}`, labels[item.risk_level] || item.risk_level)); row.append(subject, risk, el('td', '', Math.round(item.final_score)), el('td', '', `${item.url_count || 0} URL · ${item.attachment_count || 0} 附件`), el('td', '', formatDate(item.created_at))); const action = el('td'); const button = el('button', 'table-action', '查看'); button.addEventListener('click', () => openDetail(item.detection_id, item.subject)); action.append(button); row.append(action); body.append(row); }); table.append(head, body); host.append(table); } catch (error) { host.replaceChildren(el('div', 'empty-table', error.message)); handleError(error); } }
function formatDate(value) { if (!value) return '-'; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleString('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }); }
async function openDetail(id, subject) { try { const detail = await api.detectionDetail(id); $('#dialog-title').textContent = subject || '检测详情'; $('#delete-detail').dataset.detectionId = id; const content = $('#dialog-content'); content.replaceChildren(); const result = { ...detail, ...(detail.email ? { urls: detail.urls || [], attachments: detail.attachments || [] } : {}) }; const wrapper = el('div'); wrapper.append(renderResultFragment(result)); content.append(wrapper); $('#detail-dialog').showModal(); } catch (error) { handleError(error); } }
function renderResultFragment(result) { const fragment = document.createDocumentFragment(); const grid = el('div', 'detail-grid'); const e = el('section', 'detail-section'); e.append(el('h2', '', '风险证据')); (result.explanations || []).forEach(item => { const card = el('article', `explanation ${item.severity || 'warning'}`); card.append(el('b', '', `${item.code} · ${text(item.title)}`), el('p', '', text(item.detail))); if (item.evidence) card.append(el('span', 'evidence-text', item.evidence)); e.append(card); }); const a = el('section', 'detail-section'); a.append(el('h2', '', '邮件信息')); const email = result.email || {}; [['主题', email.subject], ['发件人', email.sender?.address], ['回复至', email.reply_to?.address], ['文件名', email.filename]].forEach(([k,v]) => { const row=el('div','data-row'); row.append(el('small','',k),el('b','',text(v))); a.append(row); }); if (email.text_body) { const body = el('div', 'mail-body-safe'); body.append(el('small', '', '纯文本正文')); body.append(el('p', '', email.text_body)); a.append(body); } if ((email.parse_warnings || []).length) a.append(el('div', 'warning-box', `解析提醒：${email.parse_warnings.join('；')}`)); grid.append(e,a); fragment.append(grid, renderUrls(result.urls || []), renderAttachments(result.attachments || [])); return fragment; }

async function loadBlacklist() { const host = $('#blacklist-content'); host.replaceChildren(el('div', 'loading-state', '正在读取黑名单…')); try { const data = await api.listBlacklist(state.blacklistKeyword, state.blacklistStatus); host.replaceChildren(); if (!data.items?.length) return host.append(el('div', 'empty-table', '暂无黑名单指标')); const table=el('table','data-table'), head=el('thead'), tr=el('tr'); ['指标','类型','来源','状态','命中',''].forEach(name=>tr.append(el('th','',name))); head.append(tr); const body=el('tbody'); data.items.forEach(item=>{ const row=el('tr'); row.append(el('td','subject-cell',text(item.indicator)),el('td','',item.indicator_type),el('td','',item.source)); const status=el('td'); status.append(el('span',`status-pill ${item.status}`,labels[item.status]||item.status)); row.append(status,el('td','',item.hit_count||0)); const action=el('td'); if(item.status==='active'){ const btn=el('button','table-action','停用'); btn.addEventListener('click',async()=>{try{await api.updateBlacklist(item.id,{status:'review'});showToast('已标记为待复核');loadBlacklist();}catch(error){handleError(error);}});action.append(btn);} row.append(action);body.append(row);});table.append(head,body);host.append(table);}catch(error){host.replaceChildren(el('div','empty-table',error.message));handleError(error);} }

async function loadDashboard() { try { const [data, metrics] = await Promise.all([api.overview(), api.modelMetrics().catch(() => null)]); renderMetrics(data); renderCharts(data); renderModel(metrics); } catch(error) { handleError(error); } }
function renderMetrics(data) { const host=$('#metric-grid');host.replaceChildren(); [['检测总数',data.total_detections||0,'all time'],['高风险',data.risk_counts?.high||0,'risk_level = high'],['模型倾向钓鱼',data.result_counts?.phishing||0,'result_label = phishing'],['规则命中',Object.values(data.rule_hit_counts||{}).reduce((sum,n)=>sum+n,0),'deduplicated hits']].forEach(([name,value,hint])=>{const card=el('div','panel metric-card');card.append(el('span','',name),el('b','',value),el('small','',hint));host.append(card);}); }
function renderCharts(data) { if(!window.echarts)return; const common={backgroundColor:'transparent',textStyle:{color:'#9cb0a6',fontFamily:'Segoe UI'},animationDuration:450}; const risk=echarts.init($('#risk-chart'));risk.setOption({...common,tooltip:{trigger:'item'},series:[{type:'pie',radius:['52%','74%'],itemStyle:{borderColor:'#17231e',borderWidth:4},label:{color:'#eaf4ed'},data:[{value:data.risk_counts?.high||0,name:'高风险',itemStyle:{color:'#ff7a67'}},{value:data.risk_counts?.medium||0,name:'中风险',itemStyle:{color:'#f6c85f'}},{value:data.risk_counts?.low||0,name:'低风险',itemStyle:{color:'#72d19b'}}]}]}); const dates=Object.keys(data.daily_counts||{}).sort();const trend=echarts.init($('#trend-chart'));trend.setOption({...common,grid:{left:35,right:15,top:15,bottom:28},xAxis:{type:'category',data:dates.map(d=>d.slice(5)),axisLine:{lineStyle:{color:'#2b4036'}},axisLabel:{color:'#71867b'}},yAxis:{type:'value',minInterval:1,splitLine:{lineStyle:{color:'#203229'}},axisLabel:{color:'#71867b'}},series:[{type:'line',smooth:true,symbol:'circle',symbolSize:7,data:dates.map(d=>data.daily_counts[d]),lineStyle:{color:'#d1f266',width:3},itemStyle:{color:'#d1f266'}}]}); const rules=Object.entries(data.rule_hit_counts||{}).sort((a,b)=>b[1]-a[1]).slice(0,8);const rule=echarts.init($('#rule-chart'));rule.setOption({...common,grid:{left:35,right:15,top:15,bottom:28},xAxis:{type:'category',data:rules.map(([name])=>name),axisLine:{lineStyle:{color:'#2b4036'}},axisLabel:{color:'#71867b'}},yAxis:{type:'value',minInterval:1,splitLine:{lineStyle:{color:'#203229'}},axisLabel:{color:'#71867b'}},series:[{type:'bar',barWidth:'45%',data:rules.map(([,value])=>value),itemStyle:{color:'#d1f266',borderRadius:[3,3,0,0]}}]}); window.addEventListener('resize',()=>[risk,trend,rule].forEach(chart=>chart.resize()),{once:true}); }
function renderModel(metrics) { const host=$('#model-metrics');host.replaceChildren();host.append(el('p','panel-kicker','MODEL HEALTH'),el('h2','',metrics?.model_name||'模型指标未就绪'));if(!metrics)return host.append(el('p','', '本地模型元数据暂不可用，检测接口会明确返回未就绪状态。'));host.append(el('p','model-version',`${metrics.model_version} · ${metrics.feature_version}`));const grid=el('div','model-stat-grid');[['Precision',metrics.metrics?.test_precision],['Recall',metrics.metrics?.test_recall],['F1',metrics.metrics?.test_f1],['Accuracy',metrics.metrics?.test_accuracy]].forEach(([name,value])=>{const stat=el('div','model-stat');stat.append(el('b','',value==null?'-':`${(value*100).toFixed(1)}%`),el('span','',name));grid.append(stat);});host.append(grid); }

async function loadKnowledge() { const host=$('#knowledge-content');host.replaceChildren(el('div','loading-state','正在读取知识库…'));try{const items=await api.knowledge({keyword:state.knowledgeKeyword,category:state.knowledgeCategory});host.replaceChildren();if(!items.length)return host.append(el('div','empty-table','暂无匹配内容'));items.forEach(item=>{const card=el('article','panel knowledge-card');card.append(el('span','',item.category||'GUIDE'),el('h2','',text(item.title)),el('p','',text(item.summary)));const details=document.createElement('details');details.append(el('summary','', '展开阅读'));details.append(el('p','',text(item.content)));card.append(details);host.append(card);});renderKnowledgeCategories(items);}catch(error){host.replaceChildren(el('div','empty-table',error.message));handleError(error);} }
function renderKnowledgeCategories(items) { const host=$('#knowledge-categories');const categories=['',...new Set(items.map(item=>item.category).filter(Boolean))];host.replaceChildren();categories.forEach(category=>{const button=el('button',`filter-button ${state.knowledgeCategory===category?'active':''}`,category||'全部');button.addEventListener('click',()=>{state.knowledgeCategory=category;loadKnowledge();});host.append(button);}); }

function setupNavigation() { $$('.nav-item').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.view))); $('#refresh-history').addEventListener('click',loadHistory); $$('.filter-button[data-history-risk]').forEach(button=>button.addEventListener('click',()=>{state.historyRisk=button.dataset.historyRisk;$$('.filter-button[data-history-risk]').forEach(item=>item.classList.toggle('active',item===button));loadHistory();})); $('#blacklist-search').addEventListener('input',debounce(event=>{state.blacklistKeyword=event.target.value;loadBlacklist();},350)); $('#blacklist-status').addEventListener('change',event=>{state.blacklistStatus=event.target.value;loadBlacklist();}); $('#knowledge-search').addEventListener('input',debounce(event=>{state.knowledgeKeyword=event.target.value;loadKnowledge();},350)); $('#blacklist-form').addEventListener('submit',async event=>{event.preventDefault();try{await api.createBlacklist({indicator:$('#indicator').value.trim(),indicator_type:$('#indicator-type').value,source:$('#indicator-source').value,note:$('#indicator-note').value.trim()||'',confidence:null});event.target.reset();showToast('黑名单条目已新增');loadBlacklist();}catch(error){handleError(error);}}); $('#close-dialog').addEventListener('click',()=>$('#detail-dialog').close()); $('#delete-detail').addEventListener('click',async event=>{const id=event.currentTarget.dataset.detectionId;if(!id)return;if(!window.confirm('确定删除这条检测记录吗？'))return;try{await api.deleteDetection(id);$('#detail-dialog').close();showToast('检测记录已删除');loadHistory();}catch(error){handleError(error);}}); }
function debounce(fn, wait){let timer;return(...args)=>{clearTimeout(timer);timer=setTimeout(()=>fn(...args),wait);};}

setupInput(); setupNavigation();
api.health().then(() => { $('#service-status').textContent = '本地服务已连接'; }).catch(() => { $('#service-status').textContent = '本地服务未连接'; $('.sidebar-foot').classList.add('offline'); });
